// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chat.proto

#include "chat.pb.h"
#include "chat.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace chat {

static const char* Chat_method_names[] = {
  "/chat.Chat/Talk",
};

std::unique_ptr< Chat::Stub> Chat::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Chat::Stub> stub(new Chat::Stub(channel));
  return stub;
}

Chat::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Talk_(Chat_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::chat::Message, ::chat::Message>* Chat::Stub::TalkRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::chat::Message, ::chat::Message>::Create(channel_.get(), rpcmethod_Talk_, context);
}

::grpc::ClientAsyncReaderWriter< ::chat::Message, ::chat::Message>* Chat::Stub::AsyncTalkRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::chat::Message, ::chat::Message>::Create(channel_.get(), cq, rpcmethod_Talk_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::chat::Message, ::chat::Message>* Chat::Stub::PrepareAsyncTalkRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::chat::Message, ::chat::Message>::Create(channel_.get(), cq, rpcmethod_Talk_, context, false, nullptr);
}

Chat::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Chat_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Chat::Service, ::chat::Message, ::chat::Message>(
          std::mem_fn(&Chat::Service::Talk), this)));
}

Chat::Service::~Service() {
}

::grpc::Status Chat::Service::Talk(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::chat::Message, ::chat::Message>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace chat

